[package]
name = "http_14-1"
version = "0.1.0"
authors = ["masaya.tahara <mocoso.0u1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }
